[pytest]
testpaths = tests

# Enforce strict markers, verbose output, and print test coverage for the /src directory
addopts = --strict-markers -vv -s --cov=src --cov-report=term-missing --cov-report=html --asyncio-mode=auto

# Set the environment explicitly to TEST. 
# If `settings.py` evaluates these, it will use safe default/mock values.
env =
    ENVIRONMENT=test
    DB__URI=postgresql+asyncpg://postgres:postgres@localhost:5432/test_db
    JWT_SECRET_KEY=test_secret_key_mock
    STRIPE__API_KEY=sk_test_mock
    AWS__ACCESS_KEY_ID=mock
    AWS__SECRET_ACCESS_KEY=mock

markers =
    unit: Marks test as a pure unit test (no DB).
    integration: Marks test as hitting the database/API.
    e2e: Marks test as an end-to-end full system flow.